// src/components/QrInput/CameraFeed.tsx
import CameraFeedErrorPresenter from './CameraFeedErrorPresenter';
import CameraStreamReceiver from './CameraStreamReceiver';
import CameraVideo from './CameraVideo';

export default function CameraFeed({
  autoplay,
  onReady,
}: {
  autoplay?: boolean;
  onReady?: (videoEl: HTMLVideoElement) => void;
}) {
  const hasGetUserMedia = !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia);
  const mediaDevicesSupportError = hasGetUserMedia
    ? null
    : new Error('mediaDevices is not supported');

  return (
    <CameraStreamReceiver
      renderSlot={(slotData: { stream: MediaStream | null; error: Error | null }) => (
        <>
          {mediaDevicesSupportError || slotData.error ? (
            <CameraFeedErrorPresenter
              error={mediaDevicesSupportError || slotData.error || undefined}
            />
          ) : (
            <CameraVideo
              stream={slotData.stream}
              onReady={onReady}
            />
          )}
        </>
      )}
    />
  );
}

// src/components/QrInput/CameraFeed.vue
<template>
  <CameraStreamReceiver
    v-slot="{ stream, error }"
  >
    <CameraFeedErrorPresenter
      v-if="mediaDevicesSupportError || error"
      :error="mediaDevicesSupportError || error"
    />

    <CameraVideo
      v-else
      :stream="stream"
      @ready="(videoEl: HTMLVideoElement) => $emit('ready', videoEl)"
    />
  </CameraStreamReceiver>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

import CameraVideo from './CameraVideo.vue'
import CameraFeedErrorPresenter from './CameraFeedErrorPresenter.vue'
import CameraStreamReceiver from './CameraStreamReceiver.vue'

export default defineComponent({
  components: {
    CameraVideo,
    CameraStreamReceiver,
    CameraFeedErrorPresenter,
  },

  computed: {
    hasGetUserMedia(): boolean {
      return !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia)
    },

    mediaDevicesSupportError(): Error | null {
      return this.hasGetUserMedia ? null : new Error('mediaDevices is not supported')
    },
  }
})
</script>
