// src/components/QrInput/CameraStreamReceiver.tsx
import { useState, useEffect, ReactNode } from 'react'
import CameraStreamConfigurator from './CameraStreamConfigurator'
import { CameraStreamReceiverSlotData } from './CameraStreamReceiver.lib'
import { VideoStreamConstrain } from './ConfigurationStorage'

interface CameraStreamReceiverProps {
  renderSlot?: (slotData: CameraStreamReceiverSlotData) => ReactNode
  children?: ReactNode
}

export default function CameraStreamReceiver({
  renderSlot,
  children,
}: CameraStreamReceiverProps) {
  const [error, setError] = useState<Error | null>(null)
  const [stream, setStream] = useState<MediaStream | null>(null)
  const [videoStreamConstraints, setVideoStreamConstraints] = useState<VideoStreamConstrain>(
    undefined
  )

  useEffect(() => {
    getCamera(videoStreamConstraints)
  }, [videoStreamConstraints])

  const getCamera = async (
    videoStreamConstraints: MediaStreamConstraints['video']
  ): Promise<void> => {
    setError(null)

    if (stream) {
      stream.getTracks().forEach((track) => track.stop())
    }

    try {
      const newStream = await navigator.mediaDevices.getUserMedia({
        video: videoStreamConstraints,
      })
      setStream(newStream)
    } catch (err) {
      setError(err instanceof Error ? err : null)
      setStream(null)
    }
  }

  const slotData: CameraStreamReceiverSlotData =
    error !== null
      ? {
          error,
          stream: null,
        }
      : {
          error: null,
          stream,
        }

  return (
    <div>
      <CameraStreamConfigurator
        value={videoStreamConstraints}
        onUpdateModelValue={setVideoStreamConstraints}
      />
      {renderSlot ? renderSlot(slotData) : children}
    </div>
  )
}

// src/components/QrInput/CameraStreamReceiver.vue
<template>
  <div>
    <CameraStreamConfigurator
      v-model="videoStreamConstraints"
    />
    <slot v-bind="slotData"/>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import CameraStreamConfigurator from './CameraStreamConfigurator.vue'
import { CameraStreamReceiverSlotData } from './CameraStreamReceiver.lib'
import { VideoStreamConstrain } from './ConfigurationStorage'

interface ComponentData {
  error: Error | null
  stream: MediaStream | null

  videoStreamConstraints: VideoStreamConstrain
}

export default defineComponent({
  components: {
    CameraStreamConfigurator,
  },

  data(): ComponentData {
    return {
      error: null,
      stream: null,

      videoStreamConstraints: undefined,
    }
  },

  mounted() {
    this.getCamera(this.videoStreamConstraints)
  },

  watch: {
    videoStreamConstraints: {
      handler(newConstraints: VideoStreamConstrain) {
        this.getCamera(newConstraints)
      },
      deep: true,
    },
  },

  methods: {
    async getCamera(videoStreamConstraints: MediaStreamConstraints['video']): Promise<void> {
      this.error = null

      if (this.stream) {
        this.stream.getTracks().forEach(track => track.stop())
      }

      try {
        this.stream = await navigator.mediaDevices.getUserMedia({
          video: videoStreamConstraints,
        })
      } catch (error) {
        this.error = error instanceof Error ? error : null
        this.stream = null
      }
    },
  },

  computed: {
    slotData(): CameraStreamReceiverSlotData {
      if (this.error !== null) {
        return {
          error: this.error,
          stream: null,
        }
      }

      return {
        error: null,
        stream: this.stream,
      }
    },
  }
})
</script>
