// src/components/QrInput/CameraVideo.vue
<template>
  <video
    class="video"

    ref="video"
    autoplay
    playsinline
    @loadeddata="loadeddata"
  />
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    stream: {
      type: MediaStream,
      default: null,
    }
  },

  watch: {
    stream(stream: MediaStream | null) {
      this.updateStream(stream);
    },
  },

  mounted() {
    this.updateStream(this.stream);
  },

  methods: {
    loadeddata() {
      const videoEl = (this.$refs.video as HTMLVideoElement);
      this.$emit('ready', videoEl);
    },

    updateStream(stream: MediaStream | null) {
      const videoEl = (this.$refs.video as HTMLVideoElement);
      videoEl.srcObject = stream;
    },
  },
});
</script>

<style scoped>
.video {
  width: 100%;
}
</style>

// src/components/QrInput/CameraVideo.tsx
import { useEffect, useRef } from 'react';
import { css } from '~styled-system/css';

interface CameraVideoProps {
  stream: MediaStream | null;
  onReady?: (videoEl: HTMLVideoElement) => void;
}

const cssVideo = css({ width: '100%' });

export default function CameraVideo({ stream, onReady }: CameraVideoProps) {
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const videoEl = videoRef.current;
    if (!videoEl) return;

    videoEl.srcObject = stream;
  }, [stream]);

  const handleLoadedData = () => {
    const videoEl = videoRef.current;
    if (videoEl) {
      onReady?.(videoEl);
    }
  };

  return (
    <video
      ref={videoRef}
      className={cssVideo}
      autoPlay
      playsInline
      onLoadedData={handleLoadedData}
    />
  );
}
