// src/components/QrInput/CameraStreamConfigurator.vue
<template>
  <div :class="$style.wrapper">
    <button
      @click="showConfiguratorUi = !showConfiguratorUi"
      :class="$style.button"
    >⚙</button>

    <CameraStreamConfiguratorMenu
      ref="configurator"
      :class="$style.configurator"
      v-if="showConfiguratorUi"

      :value="value"
      @input="updateConfig"
      @close="showConfiguratorUi = false"
    />

  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import CameraStreamConfiguratorMenu from './CameraStreamConfiguratorMenu.vue'
import { configStore } from './CameraStreamConfigurator.lib'
import { VideoStreamConstrain } from './ConfigurationStorage'

export default defineComponent({
  components: {
    CameraStreamConfiguratorMenu,
  },

  props: {
    value: {
      type: Object as () => VideoStreamConstrain,
      default: undefined,
    }
  },

  data() {
    return {
      showConfiguratorUi: false,
    }
  },

  created() {
    this.emitConfig()
  },

  mounted() {
    window.addEventListener('click', this.handleBackgroundClick)
  },

  beforeUnmount() {
    window.removeEventListener('click', this.handleBackgroundClick)
  },

  methods: {
    updateConfig(config: VideoStreamConstrain) {
      configStore.store(config)
      this.emitConfig()
    },

    emitConfig() {
      this.$emit('input', configStore.load())
    },

    handleBackgroundClick(event: Event): void {
      if (!this.showConfiguratorUi) return

      if ((event.composedPath() as any[]).find(x => x === this.$el)) {
        return
      }

      this.showConfiguratorUi = false
    }
  },
})
</script>

<style module>

.wrapper {
  position: absolute;
  right: 0;
  top: 0;
  z-index: 1;
}

.button {
  padding: 0.5rem;
  font-size: 1rem;
  background-color: rgba(0, 0, 0, 0);
  border: none;

  margin: 0.4em;
}

.configurator {
  position: absolute;

  right: 0;
  top: 0;

  margin: 0.4em;
  width: calc(100vw - 0px - 0.8em);

  box-sizing: border-box;
}
</style>

// src/components/QrInput/CameraStreamConfigurator.tsx
import { useState, useEffect } from 'react'
import { css } from '../../../styled-system/css'
import { configStore } from './CameraStreamConfigurator.lib'
import CameraStreamConfiguratorMenu from './CameraStreamConfiguratorMenu'
import { VideoStreamConstrain } from './ConfigurationStorage'

interface CameraStreamConfiguratorProps {
  value?: VideoStreamConstrain
  onUpdateModelValue?: (value: VideoStreamConstrain) => void
}

const cssWrapper = css({
  position: 'absolute',
  right: '0',
  top: '0',
  zIndex: '1',
})

const cssButton = css({
  padding: '0.5rem',
  fontSize: '1rem',
  backgroundColor: 'rgba(0, 0, 0, 0)',
  border: 'none',
  margin: '0.4em',
})

const cssConfigurator = css({
  position: 'absolute',
  right: '0',
  top: '0',
  margin: '0.4em',
  width: 'calc(100vw - 0px - 0.8em)',
  boxSizing: 'border-box',
})

export default function CameraStreamConfigurator({
  value,
  onUpdateModelValue,
}: CameraStreamConfiguratorProps) {
  const [showConfiguratorUi, setShowConfiguratorUi] = useState(false)

  useEffect(() => {
    emitConfig()
  }, [])

  useEffect(() => {
    window.addEventListener('click', handleBackgroundClick)
    return () => {
      window.removeEventListener('click', handleBackgroundClick)
    }
  }, [showConfiguratorUi])

  const updateConfig = (config: VideoStreamConstrain) => {
    configStore.store(config)
    emitConfig()
  }

  const emitConfig = () => {
    onUpdateModelValue?.(configStore.load())
  }

  const handleBackgroundClick = (event: MouseEvent): void => {
    if (!showConfiguratorUi) return
    setShowConfiguratorUi(false)
  }

  return (
    <div className={cssWrapper}>
      <button
        onClick={() => setShowConfiguratorUi(!showConfiguratorUi)}
        className={cssButton}
      >
        ⚙
      </button>

      {showConfiguratorUi && (
        <CameraStreamConfiguratorMenu
          className={cssConfigurator}
          value={value}
          onUpdateModelValue={updateConfig}
          onClose={() => setShowConfiguratorUi(false)}
        />
      )}
    </div>
  )
}
