// src/components/QrInput/QrInput.tsx
import { useRef, useState } from 'react'
import QrReader from './QrReader'
import CameraFeed from './CameraFeed'

interface QrInputProps {
  disabled?: boolean
  onChange?: (data: string | null) => void
}

export default function QrInput({ disabled = false, onChange }: QrInputProps) {
  const [cameraFeedVideoElement, setCameraFeedVideoElement] = useState<HTMLVideoElement | null>(null)

  return (
    <div>
      <CameraFeed
        autoplay
        onReady={setCameraFeedVideoElement}
      />
      <QrReader
        disabled={disabled}
        videoElement={cameraFeedVideoElement}
        onChange={onChange}
      />
    </div>
  )
}

// src/components/QrInput/QrInput.vue
<template>
  <div>
    <CameraFeed
      autoplay
      @ready="(el: HTMLVideoElement) => cameraFeedVideoElement = el"
    />
    <QrReader
      :disabled="disabled"
      :videoElement="cameraFeedVideoElement"
      @change="(data: any) => $emit('change', data)"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import QrReader from './QrReader.vue'
import CameraFeed from './CameraFeed.vue'

interface ComponentData {
  cameraFeedVideoElement: HTMLVideoElement | null
}

export default defineComponent({
  components: {
    QrReader,
    CameraFeed,
  },

  props: {
    disabled: {
      type: Boolean,
      default: false,
    },
  },

  data(): ComponentData {
    return {
      cameraFeedVideoElement: null,
    }
  },
})
</script>

<style scoped lang="scss">

</style>
