// src/components/QrReader.vue
<template>
  <canvas
    v-show="false"
    class="canvas"
    ref="canvas"
  />
</template>

<script lang="ts">
import Vue from 'vue';
import jsQr, { QRCode } from 'jsqr'

interface ComponentData {
  data: QRCode | null;
}

export default Vue.extend({
  props: {
    videoElement: {
      type: HTMLVideoElement,
      default: null,
    },
    scanInterval: {
      type: Number,
      default: 500,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },

  data(): ComponentData {
    return {
      data: null,
    };
  },

  computed: {
    canScan(): boolean {
      return !this.disabled && !!this.videoElement;
    }
  },

  watch: {
    data(newData) {
      this.$emit('change', newData);
    },

    videoElement(videoElement: HTMLVideoElement | null): void {
      if (!videoElement) return;

      this.setupCanvas(videoElement);
    },
  },

  methods: {
    coordinateScanning(ctx: CanvasRenderingContext2D, videoElement: HTMLVideoElement) {
      ctx.drawImage(videoElement, 0, 0, videoElement.videoWidth, videoElement.videoHeight);
      const imageData = ctx.getImageData(0, 0, videoElement.videoWidth, videoElement.videoHeight);

      return new Promise((resolve) => {
        setTimeout(() => {
          const code = jsQr(imageData.data, videoElement.videoWidth, videoElement.videoHeight);
          if (code && code.data) {
            this.data = code;
          }
          resolve();
        })
      })
    },

    async setupCanvas(videoElement: HTMLVideoElement) {
      const canvasEl = (this.$refs.canvas as HTMLCanvasElement);
      const ctx = canvasEl.getContext('2d');
      if (!ctx) {
        return;
      }

      ctx.canvas.width = videoElement.videoWidth;
      ctx.canvas.height = videoElement.videoHeight;
      ctx.clearRect(0, 0, videoElement.videoWidth, videoElement.videoHeight);

      const wait = async (duration: number) => new Promise(r => setTimeout(r, duration));

      while(this.canScan) {
        const start = performance.now();
        await this.coordinateScanning(ctx, videoElement);
        const diff = performance.now() - start;

        if (diff < this.scanInterval) {
          await wait(diff);
        }
      }
    },
  },
});
</script>

<style scoped lang="scss">
.canvas {
  width: 100%;
}
</style>

// src/components/QrInput/QrReader.tsx
import jsQR, { QRCode } from 'jsqr';
import { useEffect, useRef, useState } from 'react';
import { css } from '~styled-system/css';
import QrReaderDebug from './QrReaderDebug';

interface QrReaderProps {
  debug?: boolean;
  videoElement: HTMLVideoElement | null;
  scanInterval?: number;
  disabled?: boolean;
  onChange?: (data: string | null) => void;
}

const cssCanvas = css({ width: '100%', display: 'none' });

export default function QrReader({
  debug = false,
  videoElement,
  scanInterval = 500,
  disabled = false,
  onChange,
}: QrReaderProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [data, setData] = useState<QRCode | null>(null);
  const [isVideoReady, setIsVideoReady] = useState(false);
  const [isVideoPlaying, setIsVideoPlaying] = useState(false);
  const [isScanning, setIsScanning] = useState(false);
  const [lastError, setLastError] = useState<string | null>(null);
  const [scanCount, setScanCount] = useState(0);

  const showDebug = debug || new URLSearchParams(window.location.search).get('debug') === 'true';
  const canScan = !disabled && !!videoElement && isVideoReady && isVideoPlaying;

  useEffect(() => {
    if (data) {
      onChange?.(data.data ?? null);
    }
  }, [data, onChange]);

  useEffect(() => {
    if (!videoElement) {
      setIsVideoReady(false);
      setIsVideoPlaying(false);
      return;
    }

    const coordinateScanning = (ctx: CanvasRenderingContext2D, video: HTMLVideoElement) => {
      if (!canScan) return;

      if (video.videoWidth === 0 || video.videoHeight === 0) {
        return;
      }

      setScanCount((c) => c + 1);

      ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight);
      const imageData = ctx.getImageData(0, 0, video.videoWidth, video.videoHeight);

      try {
        const code = jsQR(imageData.data, video.videoWidth, video.videoHeight);
        if (code && code.data) {
          setData(code);
          setLastError(null);
        } else {
          setLastError('No QR found');
        }
      } catch (e) {
        setLastError(String(e));
      }
    };

    const setupCanvas = (video: HTMLVideoElement) => {
      const canvasEl = canvasRef.current;
      if (!canvasEl) return;

      const ctx = canvasEl.getContext('2d');
      if (!ctx) return;

      ctx.canvas.width = video.videoWidth;
      ctx.canvas.height = video.videoHeight;
      ctx.clearRect(0, 0, video.videoWidth, video.videoHeight);

      doScan(ctx, video);
    };

    const doScan = (ctx: CanvasRenderingContext2D, video: HTMLVideoElement) => {
      if (disabled) {
        setIsScanning(false);
        return;
      }

      setIsScanning(true);
      coordinateScanning(ctx, video);

      setTimeout(() => {
        if (!disabled) {
          doScan(ctx, video);
        }
      }, scanInterval);
    };

    const initVideo = () => {
      setIsVideoReady(true);
      if (videoElement.readyState >= 2) {
        setupCanvas(videoElement);
      }
    };

    if (videoElement.readyState >= 2) {
      initVideo();
    } else {
      videoElement.addEventListener('loadedmetadata', initVideo, { once: true });
    }

    videoElement.addEventListener(
      'playing',
      () => {
        setIsVideoPlaying(true);
        setupCanvas(videoElement);
      },
      { once: true },
    );

    return () => {
      videoElement.removeEventListener('loadedmetadata', initVideo);
    };
  }, [videoElement, scanInterval, disabled, canScan]);

  return (
    <>
      <canvas
        ref={canvasRef}
        className={cssCanvas}
      />
      {showDebug && (
        <QrReaderDebug
          videoElement={videoElement}
          isVideoReady={isVideoReady}
          isVideoPlaying={isVideoPlaying}
          isScanning={isScanning}
          videoWidth={videoElement?.videoWidth ?? 0}
          videoHeight={videoElement?.videoHeight ?? 0}
          data={data?.data ?? null}
          scanCount={scanCount}
          lastError={lastError}
        />
      )}
    </>
  );
}
