// src/pages/QrScanner.tsx
import { useState } from 'react';
import QrInput from '../components/QrInput/QrInput';
import ContentRenderer from '../components/ContentRenderer';

interface QrScannerProps {
  disabled?: boolean;
}

export default function QrScanner({ disabled = false }: QrScannerProps) {
  const [data, setData] = useState<string | null>(null);

  return (
    <div>
      <QrInput
        disabled={disabled}
        onChange={setData}
      />
      {data && <ContentRenderer data={data} />}
    </div>
  );
}

// src/pages/QrScanner.vue
<template>
  <div>
    <QrInput
      :disabled="disabled"
      @change="data = $event"
    />
    <ContentRenderer
      v-if="data"
      :data="data"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import QrInput from '@/components/QrInput/QrInput.vue'
import ContentRenderer from '@/components/ContentRenderer.vue'

interface ComponentData {
  data: string | null
}

export default defineComponent({
  components: {
    QrInput,
    ContentRenderer,
  },

  props: {
    disabled: {
      type: Boolean,
      default: false,
    },
  },

  data(): ComponentData {
    return {
      data: null,
    }
  },
})
</script>
