// src/components/ContentRenderer.tsx
import { css } from '../../styled-system/css'

interface ContentRendererProps {
  data: string | null
}

const cssContent = css({ padding: '1em' })

const cssContentText = css({
  boxShadow: '4px 4px 32px 0 rgba(0,0,0,0.25)',
  padding: '1em',
  marginBottom: '2em',
})

const cssContentAnchor = css({
  display: 'inline-block',
  fontSize: '1.25em',
  wordBreak: 'break-word',
  lineHeight: '1.25',
  textDecoration: 'none',
})

function isUrl(data: string): boolean {
  try {
    new URL(data)
    return true
  } catch {
    return false
  }
}

export default function ContentRenderer({ data }: ContentRendererProps) {
  if (!data) return null

  const url = isUrl(data)

  return (
    <div className={cssContent}>
      {url ? (
        <a
          className={`${cssContentAnchor} ${cssContentText}`}
          href={data}
          target="_blank"
          rel="noopener"
        >
          {data}
        </a>
      ) : (
        <div className={cssContentText}>
          {data}
        </div>
      )}
    </div>
  )
}

// src/components/ContentRenderer.vue
<template>
  <div class="content">
    <a
      class="content-anchor content-text"
      v-if="isUrl"
      :href="data"
      target="_blank"
      rel="noopener"
    >{{ data }}</a>
    <div
      class="content-text"
      v-else
    >
      {{ data }}
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    data: {
      type: String,
      default: null,
    },
  },
  computed: {
    isUrl() {
      try {
        new URL(this.data)
        return true;
      } catch (error) {
        return false;
      }
    },
  }
});
</script>

<style lang="scss">
.content {
  padding: 1em;
}
.content-text {
  box-shadow: 4px 4px 32px 0 rgba(0,0,0,0.25);
  padding: 1em;
  margin-bottom: 2em;
}
.content-anchor {
  display: inline-block;
  font-size: 1.25em;
  word-break: break-word;
  line-height: 1.25;
  text-decoration: none;
}
</style>
