// src/App.tsx
import { useEffect, useState } from 'react';
import { css } from '~styled-system/css';
import QrScanner from './pages/QrScanner';

const globalStyles = css({
  fontFamily: 'Avenir, Helvetica, Arial, sans-serif',
  fontSmoothing: 'antialiased',
  color: '#2c3e50',
});

export default function App() {
  const [disabled, setDisabled] = useState(false);

  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.visibilityState === 'hidden') {
        setDisabled(true);
      } else if (document.visibilityState === 'visible') {
        setDisabled(false);
      }
    };

    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => {
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, []);

  return (
    <div
      className={globalStyles}
      id="app"
    >
      <QrScanner disabled={disabled} />
    </div>
  );
}

// src/App.vue
<template>
  <div id="app">
    <QrScanner
      :disabled="disabled"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import QrScanner from '@/pages/QrScanner.vue'

export default defineComponent({
  name: 'App',
  components: {
    QrScanner,
  },

  data() {
    return {
      disabled: false
    }
  },

  mounted() {
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'hidden') {
        this.disabled = true
      } else if (document.visibilityState === 'visible') {
        this.disabled = false
      }
    })
  },
})
</script>

<style lang="scss">
body {
  margin: 0;
}

h1, h2, h3, h4, h5, h6 {
  margin-bottom: 1em;
}

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}
</style>
